src/main/com/premiersolutionshi/common/domain/BaseDomain.java
package com.premiersolutionshi.common.domain;

import org.apache.struts.action.ActionForm;

import com.premiersolutionshi.common.ui.form.BaseForm;
import com.premiersolutionshi.common.util.PrintClassPropertiesUtil;

public class BaseDomain extends ActionForm implements Domain, BaseForm {
    private static final long serialVersionUID = 7803642382107372834L;

    private Integer id;
    private Integer projectFk;
    private String action;

    @Override
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public Integer getProjectFk() {
        return projectFk;
    }

    public void setProjectFk(Integer projectFk) {
        this.projectFk = projectFk;
    }

    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    @Override
    public String toString() {
        return toString(0, true);
    }

    public String toString(int indent) {
        return toString(indent, false);
    }

    public String toString(int indent, boolean printSubDomains) {
        return PrintClassPropertiesUtil.toString(this, indent, printSubDomains);
    }

    public void copy(BaseDomain domain) {
        if (domain == null) {
            return;
        }
        setId(domain.getId());
        setProjectFk(domain.getProjectFk());
        setAction(domain.getAction());
    }
}

src/main/com/premiersolutionshi/common/domain/BasePoc.java
package com.premiersolutionshi.common.domain;

import com.premiersolutionshi.common.util.StringUtils;

/**
 * Point Of Contact
 */
public class BasePoc extends ModifiedDomain {
    private static final long serialVersionUID = -5633294857978999286L;
    private String lastName;
    private String firstName;
    private String email;
    private String workNumber;
    private Integer workNumberExt;
    private String cellNumber;
    private String faxNumber;

    public String getFullName() {
        if (StringUtils.isEmpty(firstName)) {
            return StringUtils.isEmpty(lastName) ? null : lastName;
        }
        return firstName + " " + lastName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getWorkNumber() {
        return workNumber;
    }

    public void setWorkNumber(String workNumber) {
        this.workNumber = workNumber;
    }

    public Integer getWorkNumberExt() {
        return workNumberExt;
    }

    public void setWorkNumberExt(Integer workNumberExt) {
        this.workNumberExt = workNumberExt;
    }

    public String getCellNumber() {
        return cellNumber;
    }

    public void setCellNumber(String cellNumber) {
        this.cellNumber = cellNumber;
    }

    public String getFaxNumber() {
        return faxNumber;
    }

    public void setFaxNumber(String faxNumber) {
        this.faxNumber = faxNumber;
    }
}

src/main/com/premiersolutionshi/common/domain/Customer.java
package com.premiersolutionshi.common.domain;

import java.util.ArrayList;

public class Customer extends BaseDomain {
    private static final long serialVersionUID = -9090922799453774231L;

    private String customerName;
    private ArrayList<Project> projects;

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public ArrayList<Project> getProjects() {
        return projects;
    }

    public void setProjects(ArrayList<Project> projects) {
        this.projects = projects;
    }
}

src/main/com/premiersolutionshi/common/domain/Domain.java
package com.premiersolutionshi.common.domain;

public interface Domain {

    public Integer getId();

    public void setId(Integer id);
}

src/main/com/premiersolutionshi/common/domain/FileInfo.java
package com.premiersolutionshi.common.domain;

import java.time.LocalDateTime;

import com.premiersolutionshi.common.util.DateUtils;
import com.premiersolutionshi.common.util.StringUtils;
import com.premiersolutionshi.old.util.CommonMethods;

public class FileInfo extends ModifiedDomain {
    private static final long serialVersionUID = 219885410225362329L;

    private String filename;
    private String extension;
    private String contentType;
    private Integer filesize;
    private boolean deleted;
    private String uploadedBy;
    private LocalDateTime uploadedDate;

    public void setFilesize(Integer filesize) {
        this.filesize = filesize;
    }

    public String getUploadedDateSql() {
        return DateUtils.formatToSqliteDatetime(uploadedDate);
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getExtension() {
        return extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }

    public String getSmallIcon() {
        return CommonMethods.getSmallIcon(getExtension());
    }

    public String getLargeIcon() {
        return CommonMethods.getLargeIcon(getExtension());
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * @return The size of the file, in bytes.
     */
    public Integer getFilesize() {
        return filesize;
    }

    /**
     * @return The size of the file, in bytes.
     */
    public String getFilesizeStr() {
        return StringUtils.formatBytes(filesize);
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    public String getUploadedBy() {
        return uploadedBy;
    }

    public void setUploadedBy(String uploadedBy) {
        this.uploadedBy = uploadedBy;
    }

    public LocalDateTime getUploadedDate() {
        return uploadedDate;
    }

    public String getUploadedDateStr() {
        return uploadedDate == null ? null : DateUtils.formatToBasicFormat(uploadedDate);
    }

    public void setUploadedDate(LocalDateTime uploadedDate) {
        this.uploadedDate = uploadedDate;
    }
}

src/main/com/premiersolutionshi/common/domain/JoinDomain.java
package com.premiersolutionshi.common.domain;

public class JoinDomain {

    private Integer fk1;
    private Integer fk2;

    public JoinDomain() {
    }

    public JoinDomain(Integer fk1, Integer fk2) {
        super();
        this.fk1 = fk1;
        this.fk2 = fk2;
    }

    public Integer getFk1() {
        return fk1;
    }

    public void setFk1(Integer fk1) {
        this.fk1 = fk1;
    }

    public Integer getFk2() {
        return fk2;
    }

    public void setFk2(Integer fk2) {
        this.fk2 = fk2;
    }
}

src/main/com/premiersolutionshi/common/domain/ManagedListItem.java
package com.premiersolutionshi.common.domain;

import com.premiersolutionshi.common.constant.ManagedList;

public class ManagedListItem extends SortableDomain {
    private static final long serialVersionUID = -7253871605294390137L;
    private ManagedList managedList;
    private String itemValue;
    private boolean currentDefault;
    private boolean hidden;

    public ManagedListItem() {
    }

    public ManagedListItem(String itemValue) {
        this.itemValue = itemValue;
    }

    public int getManagedListCode() {
        return managedList == null ? ManagedList.UNKNOWN.getCode() : managedList.getCode();
    }

    public void setManagedListCode(int code) {
        this.managedList = ManagedList.getByCode(code);
    }

    public ManagedList getManagedList() {
        return managedList;
    }

    public void setManagedList(ManagedList managedList) {
        this.managedList = managedList;
    }

    public String getItemValue() {
        return itemValue;
    }

    public void setItemValue(String itemValue) {
        this.itemValue = itemValue;
    }

    public boolean isCurrentDefault() {
        return currentDefault;
    }

    public void setCurrentDefault(boolean currentDefault) {
        this.currentDefault = currentDefault;
    }

    public boolean isHidden() {
        return hidden;
    }

    public void setHidden(boolean hidden) {
        this.hidden = hidden;
    }
}

src/main/com/premiersolutionshi/common/domain/PocGroup.java
package com.premiersolutionshi.common.domain;

import java.util.ArrayList;

public class PocGroup extends ModifiedDomain {
    private static final long serialVersionUID = -8119722523144662525L;
    private ArrayList<Poc> pocList;

    public String getPocEmails() {
        ArrayList<Poc> pocs = getPocList();
        if (pocs != null && !pocs.isEmpty()) {
            return buildPocEmailList(pocs);
        }
        return null;
    }

    public String getPrimaryPocEmails() {
        ArrayList<Poc> pocs = getPrimaryPocList();
        if (pocs != null && !pocs.isEmpty()) {
            return buildPocEmailList(pocs);
        }
        return null;
    }

    private String buildPocEmailList(ArrayList<Poc> pocs) {
        StringBuilder pocEmails = new StringBuilder();
        pocEmails.append(pocs.get(0).getEmail());
        int size = pocs.size();
        for (int i = 1; i < size; i++) {
            pocEmails.append("; ").append(pocs.get(i).getEmail());
        }
        return pocEmails.toString();
    }

    public ArrayList<Poc> getPocList() {
        return pocList;
    }

    public void setPocList(ArrayList<Poc> pocList) {
        this.pocList = pocList;
    }

    public ArrayList<Poc> getPrimaryPocList() {
        ArrayList<Poc> primaryPocList = new ArrayList<>();
        if (pocList != null && !pocList.isEmpty()) {
            primaryPocList = new ArrayList<>();
            for (Poc poc : pocList) {
                if (poc.isPrimaryPoc()) {
                    primaryPocList.add(poc);
                }
            }
        }
        return primaryPocList;
    }

}

src/main/com/premiersolutionshi/common/ui/form/BaseForm.java
package com.premiersolutionshi.common.ui.form;

public interface BaseForm {

    String getAction();

    public Integer getProjectFk();
}

src/main/com/premiersolutionshi/old/bean/UserBean.java
package com.premiersolutionshi.old.bean;

import java.util.ArrayList;

/**
 * Data holder for a USER form
 */
public class UserBean extends LastUpdatedBean {
    private static final long serialVersionUID = 6615818805739965896L;

    private String userPk = null;
    private String username = null;
    private String password = null;
    private String lastName = null;
    private String firstName = null;
    private String fullName = null;
    private String email = null;
    private String organization = null;
    private String currOrganization = null;
    private String title = null;
    private String workNumber = null;
    private String quickDial = null;
    private String faxNumber = null;
    private String cellNumber = null;
    private String notes = null;
    private String rank = null;
    private String[] roleArr = null;
    private String projectPk = null;
    private String[] projectPkArr = null;
    private String pocPk = null;
    private String shipPocPk = null;
    private String shipPk = null;
    private String dept = null;
    private String altEmail = null;
    private String ptoTravelPk = null;
    private String startDate = null;
    private String endDate = null;
    private String leaveType = null;
    private String location = null;
    private String isPrimaryPoc = null;
    private int size; 
    public String getAltEmail() {
        return this.altEmail;
    }

    public String getCellNumber() {
        return this.cellNumber;
    }

    public String getCurrOrganization() {
        return this.currOrganization;
    }

    public String getDept() {
        return this.dept;
    }

    public String getEmail() {
        return this.email;
    }

    public String getEndDate() {
        return this.endDate;
    }

    public String getFaxNumber() {
        return this.faxNumber;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public String getFirstNameJs() {
        return js(this.firstName);
    }

    public String getFullName() {
        return this.fullName;
    }

    public String getIsPrimaryPoc() {
        return this.isPrimaryPoc;
    }

    public boolean isPrimaryPoc() {
        return isPrimaryPoc != null && isPrimaryPoc.equals("Y");
    }

    public String getLastName() {
        return this.lastName;
    }

    public String getLastNameJs() {
        return js(this.lastName);
    }

    public String getLeaveType() {
        return this.leaveType;
    }

    public String getLocation() {
        return this.location;
    }

    public String getNotes() {
        return this.notes;
    }

    public String getOrganization() {
        return this.organization;
    }

    public String getPassword() {
        return this.password;
    }

    public String getPocPk() {
        return this.pocPk;
    }

    public String getProjectPk() {
        return this.projectPk;
    }

    public String[] getProjectPkArr() {
        return this.projectPkArr == null ? new String[0] : this.projectPkArr;
    }

    public String getPtoTravelPk() {
        return this.ptoTravelPk;
    }

    public String getQuickDial() {
        return this.quickDial;
    }

    public String getRank() {
        return this.rank;
    }

    public String[] getRoleArr() {
        return this.roleArr == null ? new String[0] : this.roleArr;
    }

    public String getShipPk() {
        return this.shipPk;
    }

    public String getShipPocPk() {
        return this.shipPocPk;
    }

    public String getStartDate() {
        return this.startDate;
    }

    public String getTitle() {
        return this.title;
    }

    public String getUsername() {
        return this.username;
    }

    public String getUsernameJs() {
        return js(this.username);
    }

    public String getUserPk() {
        return this.userPk;
    }

    public String getWorkNumber() {
        return this.workNumber;
    }

    public void setAltEmail(String altEmail) {
        this.altEmail = altEmail;
    }

    public void setCellNumber(String newCellNumber) {
        this.cellNumber = newCellNumber;
    }

    public void setCurrOrganization(String newCurrOrganization) {
        this.currOrganization = newCurrOrganization;
    }

    public void setDept(String dept) {
        this.dept = dept;
    }

    public void setEmail(String newEmail) {
        this.email = newEmail;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    public void setFaxNumber(String newFaxNumber) {
        this.faxNumber = newFaxNumber;
    }

    public void setFirstName(String newFirstName) {
        this.firstName = newFirstName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public void setIsPrimaryPoc(String isPrimaryPoc) {
        this.isPrimaryPoc = isPrimaryPoc;
    }

    public void setLastName(String newLastName) {
        this.lastName = newLastName;
    }

    public void setLeaveType(String leaveType) {
        this.leaveType = leaveType;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public void setNotes(String newNotes) {
        this.notes = newNotes;
    }

    public void setOrganization(String newOrganization) {
        this.organization = newOrganization;
    }

    public void setPassword(String newPassword) {
        this.password = newPassword;
    }

    public void setPocPk(String pocPk) {
        this.pocPk = pocPk;
    }

    public void setProjectPk(String newProjectPk) {
        this.projectPk = newProjectPk;
    }

    public void setProjectPkArr(String[] projectPkArr) {
        this.projectPkArr = projectPkArr;
    }

    public void setPtoTravelPk(String ptoTravelPk) {
        this.ptoTravelPk = ptoTravelPk;
    }

    public void setQuickDial(String newQuickDial) {
        this.quickDial = newQuickDial;
    }

    public void setRank(String newRank) {
        this.rank = newRank;
    }

    public void setRoleArr(String[] roleArr) {
        this.roleArr = roleArr;
    }

    public void setShipPk(String shipPk) {
        this.shipPk = shipPk;
    }

    public void setShipPocPk(String shipPocPk) {
        this.shipPocPk = shipPocPk;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    public void setTitle(String newTitle) {
        this.title = newTitle;
    }

    public void setUsername(String newUsername) {
        this.username = newUsername;
    }

    public void setUserPk(String newUserPk) {
        this.userPk = newUserPk;
    }

    public void setWorkNumber(String newWorkNumber) {
        this.workNumber = newWorkNumber;
 }
 
  public  int getSize(){
        return this.size;
    }
    
   public void setSize(int size) {
	    
    	this.size=size;
    }
  
 
   // Added code for Manage PTO List on home screen by Ashwini on 14-nov-2019

    private ArrayList<UserBean> list = null;
	public ArrayList<UserBean> getList()
	{
		return this.list == null ? new ArrayList<UserBean>() : this.list;
	}
	public void setList(ArrayList<UserBean> newList)
	{
		this.list = newList;
		}
	

	
}

WebContent/jsp/common/unit/unitModal.jsp
<%@ page language="java" %>
<%@ page import="com.premiersolutionshi.old.util.CommonMethods" %>

<%@ taglib prefix="bean"  uri="http://struts.apache.org/tags-bean" %>
<%@ taglib prefix="html"  uri="http://struts.apache.org/tags-html" %>
<%@ taglib prefix="logic" uri="http://struts.apache.org/tags-logic" %>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags" %>

<bean:define id="pageTitle" value="Unit Information ${unit == null ? '' : unit.fullName}"/>

<%@ include file="../../layout/old/layout-header-meta.jsp" %>
<%-- <%@ include file="../../layout/old/layout-header.jsp" %> --%>

<div class="center">
<table class="border-zero cellspacing-zero" >
<tbody>
  <tr>
    <td class="center TOP">
      <table id="detailTable" class="pshi-table-small border-zero" style="width:100%;border:1px solid #E1EAF0;">
      <thead>
        <tr>
          <th colspan="2" align="center">
            Unit Information
            <a title="Edit ${unit.fullName}" target="_blank"
              href="ship.do?action=shipEdit&shipPk=${unit.id}&projectPk=${projectPk}">
              <i class="material-icons" style="font-size:20px;">edit</i>
            </a>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="fieldName">Unit:</td>
          <td>
          <%-- Ashwini ship.do to ./ship.do --%>
            <a href="./ship.do?action=shipEdit&shipPk=${unit.id}" target="_blank">
              ${unit.shipName}
            </a><br/>
            <span style="color:#777;"><i>${unit.homeport}</i></span>
          </td>
        </tr>
        <tr>
          <td class="fieldName">Type/Hull:</td>
          <td>${unit.type} ${unit.hull}</td>
        </tr>
        <tr>
          <td class="fieldName">TYCOM:</td>
          <td>${unit.tycom}</td>
        </tr>
        <tr>
          <td class="fieldName">UIC:</td>
          <td style="white-space: nowrap;">${unit.uic}</td>
        </tr>
        <logic:notEmpty name="lastSupportVisit">
          <tr>
            <td class="fieldName">Last Support Visit:</td>
            <td>
            <%--/issue.do to ./issue.do --%>
              <a href="./issue.do?id=${lastSupportVisit.id}&projectPk=${projectPk}" target="_blank">
                ${lastSupportVisit.supportVisitDateStr} ${lastSupportVisit.category}
              </a>
              <br/>
              (Person assigned: ${lastSupportVisit.personAssigned})
            </td>
          </tr>
        </logic:notEmpty>
      </tbody>
      </table>

      <logic:notEmpty name="unit">
        <logic:notEmpty name="unit" property="pocList">
          <table class="pshi-table-small" style="width:100%">
          <thead>
            <tr>
              <th colspan="4" align="center">POCs</th>
            </tr>
            <tr>
              <th>Primary</th>
              <th>POC</th>
              <th><i class="material-icons" style="font-size:20px;">email</i></th>
              <th>Work Number</th>
            </tr>
          </thead>
          <tbody>
            <logic:iterate id="poc" name="unit" property="pocList">
              <tr>
                <td align="center">
                  ${poc.primaryPoc ? '<i class="material-icons" style="font-size:20px;color:green;">check_circle</i>' : ''}
                </td>
                <td>${poc.fullName}</td>
                <td>
                  <a href="mailto:${poc.email}" title="E-mail ${poc.email}">
                    <i class="material-icons" style="font-size:20px;">email</i>
                  </a>
                </td>
                <td align="center">
                  <logic:empty name="workNumber">--</logic:empty>
                  <logic:notEmpty name="workNumber"><a href="tel:${poc.workNumber}">${poc.workNumber}</a></logic:notEmpty>
                </td>
              </tr>
            </logic:iterate>
            <logic:empty name="unit" property="pocList">
              <tr><td colspan="4" style="text-align:center">No records found.</td></tr>
            </logic:empty>
          </tbody>
          </table>
  
          <logic:notEmpty name="unit" property="pocEmails">
            <p align="center">
              <logic:notEmpty name="unit" property="primaryPocEmails">
                <a href="mailto:${unit.primaryPocEmails}" class="btn btn-primary">
                  <i class="material-icons">email</i> Email Primary POCs
                </a>
              </logic:notEmpty>
              <a href="mailto:${unit.pocEmails}" class="btn btn-primary">
                <i class="material-icons">email</i> Email All
              </a>
            </p>
          </logic:notEmpty>
        </logic:notEmpty>
      </logic:notEmpty>
    </td>

    <td class="center TOP" style="padding-left:10px;">
      <table class="pshi-table-small border-zero" style="width:100%; border: 1px solid #E1EAF0;">
        <thead>
          <tr>
            <th colspan="2" align="center">
              Configured Systems (${configuredSystemList != null && configuredSystemList.size() > 0 ? configuredSystemList.size() : 0})
            </th>
          </tr>
        </thead>
        <logic:present name="configuredSystemList">
          <logic:iterate id="configuredSystem" name="configuredSystemList">
            <%@ include file="../../include/support/configuredSystem/configuredSystemDetailTable.jsp" %>
          </logic:iterate>
        </logic:present>
      </table>
  
      <table class="pshi-table-small" style="width:100%;">
        <thead>
          <tr>
            <th colspan="2" align="center">
              Open Issues (${issueList != null && issueList.size() > 0 ? issueList.size() : 0})
            </th>
          </tr>
          <tr>
            <th>Issue</th>
            <th>Category</th>
          </tr>
        </thead>
        <tbody>
          <logic:notEmpty name="issueList">
            <logic:iterate id="issue" name="issueList">
            <tr>
              <td>
                <div>
                  <a href="./issue.do?id=${issue.id}&projectPk=${projectPk}" target="_blank">Issue #${issue.id}</a>
                  <i>(Opened ${issue.openedDateStr})</i>
                </div>
                <div>${issue.title}</div>
              </td>
              <td>${issue.category}</td>
            </tr>
            </logic:iterate>
          </logic:notEmpty>
          <logic:empty name="issueList">
            <tr><td colspan="2" style="text-align:center">No records found.</td></tr>
          </logic:empty>
        </tbody>
        </table>
    </td>
  </tr>
</tbody>
</table>
</div>

<tags:emailDialog/>

<script type="text/javascript" src="js/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="js/jquery-ui.min.js"></script>
<script type="text/javascript" src="js/jquery.dataTables.min.js"></script>
<script src="/theme/material/js/core/popper.min.js" type="text/javascript"></script>
<script src="/theme/material/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
<script type="text/javascript" src="js/javascript.js"></script>

<%-- <%@ include file="../../layout/old/layout-footer.jsp" %> --%>

<script type="text/javascript" src="js/jquery-altcolor.js"></script>
</body>
</html>