src/main/com/premiersolutionshi/old/bean/SupportBean.java
package com.premiersolutionshi.old.bean;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.apache.struts.upload.FormFile;

import com.premiersolutionshi.old.util.CommonMethods;

/**
 * Data holder for a SUPPORT form
 */

public class SupportBean extends BaseStatusBean {
    private static final long serialVersionUID = 3158162331015867686L;
    private String issuePk = null;
    private String projectPk = null;
    private String shipPk = null;
    private String uic = null;
    private String shipName = null;
    private String type = null;
    private String hull = null;
    private String homeport = null;
    private String title = null;
    private String description = null;
    private String priority = null;
    private String issueCategoryFk = null;
    private String category = null;
    private String phase = null;
    private String currPhase = null;
    private String openedBy = null;
    private String openedDate = null;
    private String closedDate = null;
    private String personAssigned = null;
    private String currPersonAssigned = null;
    private String resolution = null;
    private String totalTime = null;
    private String createdBy = null;
    private String createdDate = null;
    private String comments = null;
    private String[] commentsArr = null;
    private ArrayList<FileBean> issueFileList = null;
    private ArrayList<FormFile> fileList = null;
    private ArrayList<SupportBean> issueCommentsList = null;
    private String[] deleteFilePkArr = null;
    private String[] relatedIssuePkArr = null;
    private String[] deleteRelatedIssuePkArr = null;
    private String issueCnt = null;
    private String openIssueCnt = null;
    private String[] taskArr = null;
    private String[] pocArr = null;
    private String supportVisitDate = null;
    private String supportVisitTime = null;
    private String supportVisitEndTime = null;
    private String logcopCnt = null;
    private String facetCnt = null;
    private String kofaxCnt = null;
    private String dummyCnt = null;
    private String updateCnt = null;
    private String laptopCnt = null;
    private String trainingCnt = null;
    private String backfileCnt = null;
    private String otherCnt = null;
    private String trainer = null;
    private String currTrainer = null;
    private String supportVisitLoc = null;
    private String supportVisitLocNotes = null;
    private String initiatedBy = null;
    private String dept = null;
    private String isEmailSent = null;
    private String isEmailResponded = null;
    private String isTrainingProvided = null;
    private String isTrainingOnsite = null;
    private String lastUpdatedBy = null;
    private String lastUpdatedDate = null;
    private String supportVisitCnt = null;
    private String[] shipPkArr = null;
    private String[] monthlyEmailArr = null;
    private String[] includeShipPkArr = null;
    private String[] reminderIssuePkArr = null;
    private String[] appliedIssuePkArr = null;
    private String[] removeIssuePkArr = null;
    private String atoPk = null;
    private String atoDate = null;
    private String atoFilename = null;
    private String totalCnt = null;
    private String appliedCnt = null;
    private String primaryPocEmails = null;
    private String pocEmails = null;
    private String autoCloseDate = null;
    private String autoCloseStatus = null;
    private String contractNumber = null;
    private String searchMode = null;
    private boolean pagination = false;
    private String sortBy = null;
    private String sortDir = null;
    private int pageNum = 1;
    private String supportVisitReason = null;
    private String[] priorityReasonArr = null;
    private String locationNotes = null;
    private String laptopIssue = null;
    private String scannerIssue = null;
    private String softwareIssue = null;
    private String[] closeIssuePkArr = null;
    private String updateFacetVersion = null;
    private String updateOsVersion = null;
    private String updateConfiguredSystemInd = null;
    private String computerName;
    private String osVersion;
    private String[] configuredSystemPkArr = null;
    private String[] includeConfiguredSystemPkArr = null;

    private Integer configuredSystemFk;

    public String getAppliedCnt() {
        return this.appliedCnt;
    }

    public String[] getAppliedIssuePkArr() {
        return this.appliedIssuePkArr;
    }

    public String getAtoDate() {
        return this.atoDate;
    }

    public String getAtoFilename() {
        return this.atoFilename;
    }

    public String getAtoPk() {
        return this.atoPk;
    }

    public String getAutoCloseDate() {
        return this.autoCloseDate;
    }

    public String getAutoCloseStatus() {
        return this.autoCloseStatus;
    }

    public String getBackfileCnt() {
        return this.backfileCnt;
    }

    public String getCategory() {
        return this.category;
    }

    public String getClosedDate() {
        return this.closedDate;
    }

    public String[] getCloseIssuePkArr() {
        return this.closeIssuePkArr;
    }

    public String getComments() {
        return this.comments;
    }

    public String[] getCommentsArr() {
        return this.commentsArr;
    }

    public List<String> getCommentsBr() {
        return Arrays.asList(CommonMethods.nes(this.comments).split("\n", -1));
    }

    public String getContractNumber() {
        return this.contractNumber;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public String getCreatedDate() {
        return this.createdDate;
    }

    public String getCurrPersonAssigned() {
        return this.currPersonAssigned;
    }

    public String getCurrPhase() {
        return this.currPhase;
    }

    public String getCurrTrainer() {
        return this.currTrainer;
    }

    public String[] getDeleteFilePkArr() {
        return this.deleteFilePkArr;
    }

    public String[] getDeleteRelatedIssuePkArr() {
        return this.deleteRelatedIssuePkArr;
    }

    public void getDeleteRelatedIssuePkArr(String[] deleteRelatedIssuePkArr) {
        this.deleteRelatedIssuePkArr = deleteRelatedIssuePkArr;
    }

    public String getDept() {
        return this.dept;
    }

    public String getDescription() {
        return this.description;
    }

    public List<String> getDescriptionBr() {
        return Arrays.asList(CommonMethods.nes(this.description).split("\n", -1));
    }

    public String getDummyCnt() {
        return this.dummyCnt;
    }

    public String getFacetCnt() {
        return this.facetCnt;
    }

    public ArrayList<FormFile> getFileList() {
        return this.fileList;
    }

    public String getHomeport() {
        return this.homeport;
    }

    public String getHull() {
        return this.hull;
    }

    public String[] getIncludeShipPkArr() {
        return this.includeShipPkArr;
    }

    public String getInitiatedBy() {
        return this.initiatedBy;
    }

    public String getIsEmailResponded() {
        return this.isEmailResponded;
    }

    public String getIsEmailSent() {
        return this.isEmailSent;
    }

    public String getIssueCategoryFk() {
        return this.issueCategoryFk;
    }

    public String getIssueCnt() {
        return this.issueCnt;
    }

    public ArrayList<SupportBean> getIssueCommentsList() {
        return this.issueCommentsList;
    }

    public ArrayList<FileBean> getIssueFileList() {
        return this.issueFileList;
    }

    public String getIssuePk() {
        return this.issuePk;
    }

    public String getIsTrainingOnsite() {
        return this.isTrainingOnsite;
    }

    public String getIsTrainingProvided() {
        return this.isTrainingProvided;
    }

    public String getKofaxCnt() {
        return this.kofaxCnt;
    }

    public String getLaptopCnt() {
        return this.laptopCnt;
    }

    public String getLaptopIssue() {
        return this.laptopIssue;
    }

    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    public String getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }

    public String getLocationNotes() {
        return this.locationNotes;
    }

    public String getLogcopCnt() {
        return this.logcopCnt;
    }

    public String[] getMonthlyEmailArr() {
        return this.monthlyEmailArr;
    }

    public String getOpenedBy() {
        return this.openedBy;
    }

    public String getOpenedDate() {
        return this.openedDate;
    }

    public String getOpenIssueCnt() {
        return this.openIssueCnt;
    }

    public String getOtherCnt() {
        return this.otherCnt;
    }

    public int getPageNum() {
        return this.pageNum;
    }

    public String getPersonAssigned() {
        return this.personAssigned;
    }

    public String getPhase() {
        return this.phase;
    }

    public String[] getPocArr() {
        return this.pocArr;
    }

    public String getPocEmails() {
        return this.pocEmails;
    }

    public String getPrimaryPocEmails() {
        return this.primaryPocEmails;
    }

    public String getPriority() {
        return this.priority;
    }

    public String getPriorityReason() {
        if (this.priorityReasonArr == null) {
            return null;
        }
        StringBuilder str = new StringBuilder();
        for (String priorityReason : this.priorityReasonArr) {
            if (str.length() > 0) {
                str.append(", ");
            }
            str.append(priorityReason);
            if ((priorityReason.equals("Laptop Down")) && (!CommonMethods.isEmpty(this.laptopIssue))) {
                str.append(" (" + this.laptopIssue + ")");
            }
            else if ((priorityReason.equals("Scanner Down")) && (!CommonMethods.isEmpty(this.scannerIssue))) {
                str.append(" (" + this.scannerIssue + ")");
            }

src/main/com/premiersolutionshi/support/domain/AtoUpdate.java
package com.premiersolutionshi.support.domain;

import java.time.LocalDate;

import com.premiersolutionshi.common.domain.ModifiedDomain;
import com.premiersolutionshi.common.util.DateUtils;

public class AtoUpdate extends ModifiedDomain {
    private static final long serialVersionUID = -5030884975014440879L;

    private Integer projectFk;
    private LocalDate atoDate;
    private LocalDate openedDate;
    private String comments;
    private String label;
    private int totalIssues;
    private int totalIssuesClosed; //applied_cnt (in the old code)

    public String getLabel() {
        if (label == null) {
            label = "ATOUpdates_" + DateUtils.formatToPattern(getAtoDate(), "yyyyMMdd");
        }
        return label;
    }

    public Integer getProjectFk() {
        return projectFk;
    }

    public void setProjectFk(Integer projectFk) {
        this.projectFk = projectFk;
    }

    public LocalDate getAtoDate() {
    	
    	/* Changes start by Ashwini  */
    	atoDate=LocalDate.now();
    	
    	/*Change end*/
        return atoDate;
    }

    public void setAtoDate(LocalDate atoDate) {
        this.atoDate = atoDate;
    }

    public LocalDate getOpenedDate() {
        return openedDate;
    }

    public String getOpenedDateSql() {
        return DateUtils.formatToSqliteDate(openedDate);
    }

    public String getAtoDateSql() {
        return DateUtils.formatToSqliteDate(atoDate);
    }

    public void setOpenedDate(LocalDate openedDate) {
        this.openedDate = openedDate;
    }

    public String getAtoDateStr() {
        return atoDate == null ? DateUtils.getNowInBasicFormat() : DateUtils.COMMON_BASIC_FORMAT.format(atoDate);
    }

    public void setAtoDateStr(String atoDateStr) {
        setAtoDate(DateUtils.parseBasicDate(atoDateStr));
    }

    public String getOpenedDateStr() {
        return openedDate == null ? DateUtils.getNowInBasicFormat() : DateUtils.COMMON_BASIC_FORMAT.format(openedDate);
    }

    public void setOpenedDateStr(String openedDateStr) {
        setOpenedDate(DateUtils.parseBasicDate(openedDateStr));
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public int getTotalIssues() {
        return totalIssues;
    }

    public void setTotalIssues(int totalIssues) {
        this.totalIssues = totalIssues;
    }

    public int getTotalIssuesClosed() {
        return totalIssuesClosed;
    }

    public void setTotalIssuesClosed(int totalIssuesClosed) {
        this.totalIssuesClosed = totalIssuesClosed;
    }
}

src/main/com/premiersolutionshi/support/domain/ConfiguredSystemLocHist.java
package com.premiersolutionshi.support.domain;

import java.time.LocalDate;

import com.premiersolutionshi.common.domain.ModifiedDomain;
import com.premiersolutionshi.common.util.DateUtils;

public class ConfiguredSystemLocHist extends ModifiedDomain {
    private static final long serialVersionUID = 6757927795755229109L;

    private int configuredSystemFk;
    private String location;
    private LocalDate locationDate;
    private String reason;

    public String getLocationDateSql() {
        return DateUtils.formatToSqliteDate(locationDate);
    }

    public int getConfiguredSystemFk() {
        return configuredSystemFk;
    }

    public void setConfiguredSystemFk(int configuredSystemFk) {
        this.configuredSystemFk = configuredSystemFk;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public LocalDate getLocationDate() {
        return locationDate;
    }

    public void setLocationDate(LocalDate locationDate) {
        this.locationDate = locationDate;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }
}

src/main/com/premiersolutionshi/support/domain/FacetVersion.java
package com.premiersolutionshi.support.domain;

import com.premiersolutionshi.common.domain.SortableDomain;
import com.premiersolutionshi.common.util.StringUtils;

public class FacetVersion extends SortableDomain {
    private static final long serialVersionUID = 7109055379750983700L;
    private boolean current;

    public String getIsCurr() {
        return current ? "Y" : "N";
    }

    public void setIsCurr(String isCurr) {
        this.current = !StringUtils.isEmpty(isCurr) && isCurr.equals("Y");
    }
}

src/main/com/premiersolutionshi/support/domain/FkAndCount.java
package com.premiersolutionshi.support.domain;

public class FkAndCount {
    private String fk;
    private Integer count;

    public String getFk() {
        return fk;
    }

    public void setFk(String fk) {
        this.fk = fk;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }
}

src/main/com/premiersolutionshi/support/domain/FkAndStringList.java
package com.premiersolutionshi.support.domain;

import java.util.ArrayList;

public class FkAndStringList {
    private Integer fk;
    private ArrayList<String> stringList;

    public Integer getFk() {
        return fk;
    }

    public void setFk(Integer fk) {
        this.fk = fk;
    }

    public ArrayList<String> getStringList() {
        return stringList;
    }

    public void setStringList(ArrayList<String> stringList) {
        this.stringList = stringList;
    }
}

src/main/com/premiersolutionshi/support/domain/IssueCategory.java
package com.premiersolutionshi.support.domain;

import com.premiersolutionshi.common.domain.ModifiedDomain;

public class IssueCategory extends ModifiedDomain {
    private static final long serialVersionUID = -5275025036519892559L;

    private String category;

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }
}

src/main/com/premiersolutionshi/support/domain/IssueStatusDomain.java
package com.premiersolutionshi.support.domain;

import com.premiersolutionshi.common.domain.ModifiedDomain;
import com.premiersolutionshi.support.constant.IssueStatus;

public class IssueStatusDomain extends ModifiedDomain {
    private static final long serialVersionUID = -4713944812124969755L;

    private IssueStatus issueStatus;

    public int getStatusCode() {
        return getIssueStatus().getCode();
    }

    public void setStatusCode(int statusCode) {
        this.issueStatus = IssueStatus.getByCode(statusCode);
    }

    public IssueStatus getIssueStatus() {
        return issueStatus == null ? IssueStatus.NEW : issueStatus;
    }

    public void setIssueStatus(IssueStatus issueStatus) {
        this.issueStatus = issueStatus;
    }

    public String getStatusCss() {
        return getIssueStatus().getColor();
    }

    public String getStatus() {
        return issueStatus == null ? IssueStatus.NEW.getName() : issueStatus.getName();
    }

    public void setStatus(String statusStr) {
        this.issueStatus = IssueStatus.getByName(statusStr);
    }

    public boolean isClosed() {
        if (issueStatus != null && issueStatus.isClosed()) {
            return true;
        }
        return false;
    }
}

src/main/com/premiersolutionshi/support/domain/SupportVisit.java
package com.premiersolutionshi.support.domain;

import java.time.LocalDate;

public class SupportVisit {

    private LocalDate visitDate;
    private String loc;
    private Integer time;
    private Integer endTime;
    private String reason;
    private String locNotes;
}

WebContent/jsp/support/issueList.jsp
<!DOCTYPE html>
<%@ page language="java" %>
<%@ page import="com.premiersolutionshi.old.util.CommonMethods" %>

<%@ taglib prefix="bean"  uri="http://struts.apache.org/tags-bean" %>
<%@ taglib prefix="html"  uri="http://struts.apache.org/tags-html" %>
<%@ taglib prefix="logic" uri="http://struts.apache.org/tags-logic" %>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags" %>

<bean:define id="defaultPageTitle" value="Support Issue List"/>
<jsp:useBean id="customPageTitle" scope="request" class="java.lang.String"/><bean:define id="pageTitle" name="customPageTitle"/><logic:equal name="pageTitle" value=""><bean:define id="pageTitle" name="defaultPageTitle"/></logic:equal>
<jsp:useBean id="loginBean" scope="request" class="com.premiersolutionshi.old.bean.LoginBean"/>

<jsp:useBean id="projectPk" scope="request" class="java.lang.String"/>

<jsp:useBean id="inputBean"               scope="request" class="com.premiersolutionshi.old.bean.SupportBean"/>

<jsp:useBean id="searchMode"               scope="request" class="java.lang.String"/>
<jsp:useBean id="uic"                     scope="request" class="java.lang.String"/>
<jsp:useBean id="issueList"               scope="request" class="java.util.ArrayList"/>

<jsp:useBean id="summaryByMonthList"       scope="request" class="java.util.ArrayList"/>
<jsp:useBean id="summaryByShipList"       scope="request" class="java.util.ArrayList"/>
<jsp:useBean id="totalByShipBean"         scope="request" class="com.premiersolutionshi.old.bean.SupportBean"/>

<jsp:useBean id="recentIssueTotal"         scope="request" class="java.lang.String"/>
<jsp:useBean id="recentIssueSummaryList"   scope="request" class="java.util.ArrayList"/>
<jsp:useBean id="recentIssueList"         scope="request" class="java.util.ArrayList"/>
<jsp:useBean id="recentClosedTotal"       scope="request" class="java.lang.String"/>
<jsp:useBean id="recentClosedList"         scope="request" class="java.util.ArrayList"/>

<jsp:useBean id="configuredSystemList"     scope="request" class="java.util.ArrayList"/>
<jsp:useBean id="contractNumberList"       scope="request" class="java.util.ArrayList"/>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>TrackIT - ${pageTitle}</title>

  <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css"/>
  <link rel="stylesheet" type="text/css" href="css/stylesheet.css"/>
  <link rel="stylesheet" type="text/css" href="css/jquery-ui.min.css"/>
  <link rel="stylesheet" type="text/css" href="css/jquery.dataTables.min.css"/>
</head>

<body>
<%@ include file="../include/app-header.jsp" %>
<div class="colmask leftmenu"><div class="colright">
  <div class="col1wrap"><div class="col1">
    <%@ include file="../include/content-header.jsp" %>

    <tags:projectPkBreadcrumb projectPk="${projectPk}" pageTitle="${pageTitle}" hideOptions="true" />

    <table class="issue-list-control-panel">
      <tbody><tr>
        <% if (contractNumberList.size() > 0) { %>
        <td>
            <form class="form-inline" action="support.do" method="GET">
              <input type="hidden" name="action" value="issueList"/>
              <input type="hidden" name="searchPerformed" value="Y"/>
              <input type="hidden" name="projectPk" value="${projectPk}"/>
              <div class="form-group">
                <label for="contractNumber">Contract Number:</label>
                <html:select name="inputBean" property="contractNumber" styleClass="form-control input-sm">
                  <html:option value="">View All</html:option>
                  <html:options name="contractNumberList"/>
                </html:select>
              </div>
              <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span> Search</button>
            </form>
        </td>
        <% } %>
        <td>
          <a href="export.do?action=issueListXlsx&type=${searchMode}&projectPk=${projectPk}" class="btn btn-default"><img src="images/file_icons/sml_file_xls.gif"/> Export to Excel</a>
          <a href="support.do?action=issueReports&projectPk=${projectPk}" class="btn btn-default"><img src="images/sml_chart.png"/> Reports</a>
        </td>
        <td>
          <%@ include file="../include/support/issue/jumpToIssuePk.jsp" %>
        </td>
        <td>
          <a href="issue.do?action=add&projectPk=${projectPk}&pageFrom=issueList" class="btn btn-success">
            <span class="glyphicon glyphicon-plus"></span>
            Add Issue
          </a>
        </td>
      </tr></tbody>
    </table>

    <div>
      <div id="radio" align="center" style="display:none;">
        <input type="radio" name="searchMode" id="radio_open_non_monthly" value="open_non_monthly"/><label for="radio_open_non_monthly">Open (Non-Monthly)</label>
        <input type="radio" name="searchMode" id="radio_all_non_monthly_60" value="all_non_monthly_60"/><label for="radio_all_non_monthly_60">All Non-Monthly (last 60 days)</label>
        <input type="radio" name="searchMode" id="radio_open" value="open"/><label for="radio_open">All Open</label>
        <input type="radio" name="searchMode" id="radio_facetupdate" value="facetupdate"/><label for="radio_facetupdate">Open FACET Updates</label>
        <input type="radio" name="searchMode" id="radio_ato" value="ato"/><label for="radio_ato">Open ATO</label>
        <input type="radio" name="searchMode" id="radio_dms" value="dms"/><label for="radio_dms">Open DMS</label>
        <input type="radio" name="searchMode" id="radio_dacsinactivity" value="dacsinactivity"/><label for="radio_dacsinactivity">Open DACS Inactivity</label>
        <input type="radio" name="searchMode" id="radio_dacsmissingtransmittal" value="dacsmissingtransmittal"/><label for="radio_dacsmissingtransmittal">Open Missing Transmittals</label>
        <input type="radio" name="searchMode" id="radio_ship" value="ship"/><label for="radio_ship">By Unit</label>
      </div>
      <div id="ship_div" style="display:none;font-size:100%;" align="center">
        <br/>
        Select Unit:
        <html:select name="inputBean" property="uic" styleId="uic" style="font-size:inherit;">
          <html:options collection="configuredSystemList" property="uic" labelProperty="shipName"/>
        </html:select>
        <button id="ship_btn" style="font-size:inherit;">Go</button>
      </div>
    </div><br/>

    <% if (issueList.size() == 0) { %>
      <p class="error" align="center">
      No Issues Found
      </p>
    <% } else { %>
      <p align="center">
      <div class="center">
      <table id="issueTable" class="stripe row-border border-zero cellspacing-zero">
      <thead>
        <tr>
          <th>#</th>
          <th>Title/Summary</th>
          <th>Status</th>
          <th>Unit Name</th>
          <th>Category</th>
          <th>Opened<br/>Date</th>
          <th>Person<br/>Assigned</th>
          <th>Last Updated Date</th>
          <th>Last Updated By</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
      <logic:iterate id="resultBean" name="issueList" type="com.premiersolutionshi.old.bean.SupportBean">
        <% if (CommonMethods.nes(resultBean.getPriority()).equals("High")) { %>
          <tr style="vertical-align:top;" align="left" class="highpriority">
        <% } else { %>
          <tr style="vertical-align:top;" align="left">
        <% } %>
          <td align="center"><a href="issue.do?id=${resultBean.issuePk}&projectPk=${projectPk}&pageFrom=issueList">${resultBean.issuePk}</a></td>
          <td style="width:250px">
            <a href="issue.do?id=${resultBean.issuePk}&projectPk=${projectPk}&pageFrom=issueList"><b>Issue #${resultBean.issuePk}</b></a>
            <% if (CommonMethods.nes(resultBean.getPriority()).equals("High")) { %>
              &nbsp;<span style="color:#f00;font-weight:bold;">HIGH PRIORITY</span>
            <% } %>
            <br/>
            ${resultBean.title}
          </td>
          <td style="${resultBean.statusCss} width:175px">
            ${resultBean.status}<br/>
            <i>${resultBean.resolution}</i>
          </td>
          <td title="Unit Name">
            ${resultBean.shipName}<br/>
            <span style="color:#777;font-style:italic;">${resultBean.homeport}</span>
          </td>
          <td>${resultBean.category}</td>
          <td align="center">${resultBean.openedDate}</td>
          <td>${resultBean.personAssigned}</td>
          <td style="font-style:italic;">${resultBean.lastUpdatedDate}</td>
          <td style="font-style:italic;">${resultBean.lastUpdatedBy}</td>
          <td nowrap align="center">
            <a href="issue.do?action=edit&id=${resultBean.issuePk}&projectPk=${projectPk}&pageFrom=issueList"><img src="images/icon_edit.png" title="Edit Issue #${resultBean.issuePk}"/></a>
            &nbsp;<a href="issue.do?action=copy&id=${resultBean.issuePk}&projectPk=${projectPk}&pageFrom=issueList"><img src="images/icon_copy.png" title="Copy Issue #${resultBean.issuePk}"/></a>
            &nbsp;<a href="support.do?action=issueDeleteDo&issuePk=${resultBean.issuePk}&projectPk=${projectPk}&pageFrom=issueList" onclick="return confirmDelete('${resultBean.issuePk}');"><img src="images/icon_delete.png" title="Delete Issue #${resultBean.issuePk}"/></a>
          </td>
        </tr>
      </logic:iterate>
      </tbody>
      </table>
      </div>

      <p>
        <a href="support.do?action=generateFeedbackForm&projectPk=${projectPk}">
          <img src="images/file_icons/file_txt.png"/>
          <br/>Generate Support Feedback Form
        </a>
      </p>
    <% } %>
  </div></div>

  <%@ include file="../include/app-col2.jsp" %>
</div></div>

<%@ include file="../include/app-footer.jsp" %>

<script type="text/javascript" src="js/jquery-ui.min.js"></script>
<script type="text/javascript" src="js/jquery.dataTables.min.js"></script>

<script type="text/javascript">
  $(function() {
    $('input:radio[name="searchMode"]').checkboxradio({
      icon: false
    });

    var table = $('#issueTable').DataTable( {
      "dom": "<'row'<'col-sm-3'l><'col-sm-3'f><'col-sm-6'p>>" +
            "<'row'<'col-sm-12'tr>>" +
            "<'row'<'col-sm-5'i><'col-sm-7'p>>",
      "order": [[ 0, "desc" ]],
      "lengthMenu": [[10, 50, 100, -1], [10, 50, 100, "All"]],
      "pageLength": 50,
      "columnDefs": [
        { orderable: false, targets: 1 },
        { orderable: false, targets: 9 },
        { type: "date", targets: 5 }, //Opened Date
        { type: "date", targets: 7 }, //Last Updated Date
      ],
      "aoColumns": [
        { "orderSequence": [ "desc", "asc", "asc" ] },
        null,
        null,
        null,
        null,
        { "orderSequence": [ "desc", "asc", "asc" ] },
        null,
        { "orderSequence": [ "desc", "asc", "asc" ] },
        null,
        null
      ],
      stateSave: false
    });

    $('#radio').on('change', function(event) {
      if ($('input:radio[name="searchMode"]:checked').val() == 'ship') {
        $('#ship_div').show();
      } else {
        window.location.href = 'support.do?action=issueList&searchMode=' + $('input:radio[name="searchMode"]:checked').val() + '&projectPk=${projectPk}';
      }
    });

    $('#ship_btn').on('click', function(event) {
      window.location.href = 'support.do?action=issueList&searchMode=ship&projectPk=${projectPk}&uic=' + $('#uic').val();
    });
  });

  $(document).ready(function () {
    $('#radio_${searchMode}').prop('checked', true);
    $('#radio').buttonset();
    $('#radio').show();

    if ($('input:radio[name="searchMode"]:checked').val() == 'ship') {
      $('#ship_div').show();
      $('#uic').val('${uic}');
    } else {
      $('#ship_div').hide();
    }
  });

  function confirmDelete(issuePk) {
    return confirm("Are you sure you want to delete issue #" + issuePk);
  }
</script>

</body>
</html>